/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 7c4b2137ffe996a35900cd4c73d3c215)
interface __BaseEnv_Env {
	INSTALLATION_ID: "home-prototype";
	AUDIO_PROVIDER: "openai";
	WalleAgent: DurableObjectNamespace<import("./src/index").WalleAgent>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "WalleAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "INSTALLATION_ID" | "AUDIO_PROVIDER">> {}
}
