/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 64cbd5133dc9837079ae4169d1d4ab67)
interface __BaseEnv_Env {
	BROWSER: BrowserRun;
	INSTALLATION_ID: "home-prototype";
	AUDIO_PROVIDER: "openai";
	DEVICE_TOKEN: string;
	BRIDGE_TOKEN: string;
	WalleAgent: DurableObjectNamespace<import("./src/index").WalleAgent>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "WalleAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "INSTALLATION_ID" | "AUDIO_PROVIDER" | "DEVICE_TOKEN" | "BRIDGE_TOKEN">> {}
}
