/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 72d09bf7fed94be6e392a48612c338c7)
interface __BaseEnv_Env {
	INSTALLATION_ID: "home-prototype";
	WalleAgent: DurableObjectNamespace<import("./src/index").WalleAgent>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "WalleAgent";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "INSTALLATION_ID">> {}
}
