#pragma once

#include <stdint.h>

typedef enum {
    FACE_SPRITE_HEAD_BLANK = 0,
    FACE_SPRITE_ANTENNA = 1,
    FACE_SPRITE_EAR_LEFT = 2,
    FACE_SPRITE_EAR_RIGHT = 3,
    FACE_SPRITE_EYE_OPEN_LEFT = 4,
    FACE_SPRITE_EYE_OPEN_RIGHT = 5,
    FACE_SPRITE_EYE_HALF_LEFT = 6,
    FACE_SPRITE_EYE_HALF_RIGHT = 7,
    FACE_SPRITE_EYE_WORRIED_LEFT = 8,
    FACE_SPRITE_EYE_WORRIED_RIGHT = 9,
    FACE_SPRITE_EYE_DEVIOUS_LEFT = 10,
    FACE_SPRITE_EYE_DEVIOUS_RIGHT = 11,
    FACE_SPRITE_EYE_ANGRY_LEFT = 12,
    FACE_SPRITE_EYE_ANGRY_RIGHT = 13,
    FACE_SPRITE_EYE_TEARY_LEFT = 14,
    FACE_SPRITE_EYE_TEARY_RIGHT = 15,
    FACE_SPRITE_EYE_HAPPY_CLOSED_LEFT = 16,
    FACE_SPRITE_EYE_HAPPY_CLOSED_RIGHT = 17,
    FACE_SPRITE_EYE_SLEEP_CLOSED_LEFT = 18,
    FACE_SPRITE_EYE_SLEEP_CLOSED_RIGHT = 19,
    FACE_SPRITE_PUPIL_SMALL = 20,
    FACE_SPRITE_PUPIL_MEDIUM = 21,
    FACE_SPRITE_PUPIL_LARGE = 22,
    FACE_SPRITE_PUPIL_HEART = 23,
    FACE_SPRITE_MOUTH_SMILE_GENTLE = 24,
    FACE_SPRITE_MOUTH_SMILE_WIDE = 25,
    FACE_SPRITE_MOUTH_OPEN_SMALL = 26,
    FACE_SPRITE_MOUTH_TALK_OVAL = 27,
    FACE_SPRITE_MOUTH_TALK_WIDE = 28,
    FACE_SPRITE_MOUTH_SURPRISED_O = 29,
    FACE_SPRITE_MOUTH_FROWN_FLAT = 30,
    FACE_SPRITE_MOUTH_FROWN_ANGRY_OPEN = 31,
    FACE_SPRITE_MOUTH_SAD_SOFT = 32,
    FACE_SPRITE_MOUTH_SMIRK = 33,
    FACE_SPRITE_MOUTH_SLEEPY_POUT = 34,
    FACE_SPRITE_BROW_RAISED_LEFT = 35,
    FACE_SPRITE_BROW_RAISED_RIGHT = 36,
    FACE_SPRITE_BROW_SOFT_LEFT = 37,
    FACE_SPRITE_BROW_SOFT_RIGHT = 38,
    FACE_SPRITE_BROW_SLANT_LEFT = 39,
    FACE_SPRITE_BROW_SLANT_RIGHT = 40,
    FACE_SPRITE_ACCENT_Z_LARGE = 41,
    FACE_SPRITE_ACCENT_Z_SMALL = 42,
    FACE_SPRITE_ACCENT_SOUND_WAVE_SMALL = 43,
    FACE_SPRITE_COUNT,
} face_sprite_id_t;

typedef struct {
    uint16_t width;
    uint16_t height;
    int16_t sheet_x;
    int16_t sheet_y;
    const uint16_t *pixels;
    const uint8_t *alpha;
} face_sprite_asset_t;

extern const face_sprite_asset_t g_face_sprites[FACE_SPRITE_COUNT];
