#!/usr/bin/env python3
"""Interactively create the ignored ESP32 prototype credentials header."""

from __future__ import annotations

import getpass
import json
import os
from pathlib import Path
import sys
import tempfile

REPO_ROOT = Path(__file__).resolve().parent.parent
OUTPUT = REPO_ROOT / "firmware" / "main" / "credentials.h"
TOKEN_FILE = (
    Path.home()
    / "Library"
    / "Application Support"
    / "Walle"
    / "secrets"
    / "device-token.txt"
)
RELAY_HOST = "walle-relay.matt-ce8.workers.dev"
RELAY_PATH = "/v1/device"


def prompt_network(name: str, *, optional: bool) -> tuple[str, str] | None:
    while True:
        suffix = " (leave blank to skip)" if optional else ""
        ssid = input(f"{name} Wi-Fi SSID{suffix}: ").strip()
        if optional and not ssid:
            return None
        length = len(ssid.encode("utf-8"))
        if not 1 <= length <= 32:
            print("SSID must be between 1 and 32 UTF-8 bytes.", file=sys.stderr)
            continue
        break

    while True:
        password = getpass.getpass(
            f"{name} Wi-Fi password (hidden; blank only for an open network): "
        )
        length = len(password.encode("utf-8"))
        if length == 0 or 8 <= length <= 64:
            return ssid, password
        print(
            "Password must be blank for an open network or 8-64 UTF-8 bytes.",
            file=sys.stderr,
        )


def c_string(value: str) -> str:
    # JSON string escaping is compatible with these UTF-8 C string literals.
    return json.dumps(value, ensure_ascii=False)


def main() -> int:
    print("Walle device credential setup")
    print("Secrets are written only to ignored firmware/main/credentials.h.")
    print("Passwords are hidden while typing.")
    print("This setup supports open or WPA/WPA2/WPA3-Personal networks.")
    print("Stop here if the office uses a captive portal or enterprise username/certificate.\n")

    if not TOKEN_FILE.is_file():
        print(
            f"Device token not found at {TOKEN_FILE}. Deploy/configure the relay first.",
            file=sys.stderr,
        )
        return 1
    token = TOKEN_FILE.read_text(encoding="utf-8").strip()
    if len(token) < 32 or any(char.isspace() for char in token):
        print("Stored device token is malformed; refusing to write it.", file=sys.stderr)
        return 1

    home = prompt_network("Home", optional=False)
    office = prompt_network("Office", optional=True)
    assert home is not None
    networks = [home] + ([office] if office is not None else [])

    if OUTPUT.exists():
        answer = input(f"\n{OUTPUT} already exists. Replace it? [y/N]: ").strip().lower()
        if answer not in {"y", "yes"}:
            print("No changes made.")
            return 0

    lines = [
        "// Generated by tools/configure-device.py. DO NOT COMMIT.",
        "// Prototype secrets are embedded in flash; physical extraction remains possible.",
        "#pragma once",
        "",
        f"#define WALLE_WIFI_NETWORK_COUNT {len(networks)}",
    ]
    for index, (ssid, password) in enumerate(networks):
        lines.extend(
            [
                f"#define WALLE_WIFI_SSID_{index} {c_string(ssid)}",
                f"#define WALLE_WIFI_PASSWORD_{index} {c_string(password)}",
            ]
        )
    lines.extend(
        [
            "",
            f"#define WALLE_RELAY_HOST {c_string(RELAY_HOST)}",
            f"#define WALLE_RELAY_PATH {c_string(RELAY_PATH)}",
            f"#define WALLE_DEVICE_TOKEN {c_string(token)}",
            "",
        ]
    )

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    fd, temporary_name = tempfile.mkstemp(
        prefix=".credentials.", suffix=".tmp", dir=OUTPUT.parent
    )
    try:
        os.fchmod(fd, 0o600)
        with os.fdopen(fd, "w", encoding="utf-8") as output:
            output.write("\n".join(lines))
        os.replace(temporary_name, OUTPUT)
        os.chmod(OUTPUT, 0o600)
    finally:
        try:
            os.unlink(temporary_name)
        except FileNotFoundError:
            pass

    network_source = REPO_ROOT / "firmware" / "main" / "network_relay.c"
    if network_source.exists():
        os.utime(network_source, None)

    print(f"\nConfigured {len(networks)} Wi-Fi network(s) in {OUTPUT}.")
    print("The file is ignored by Git and has owner-only permissions.")
    print("Firmware support for selecting and connecting to these entries is next.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
